-- ============================================================================
-- Aldi Triantama Pixel Portfolio — Consolidated Supabase Schema
-- ============================================================================
-- Jalankan seluruh file ini sekali jalan di:
--   Supabase Dashboard -> SQL Editor -> New query -> paste semua ini -> Run
--
-- Aman dijalankan ulang (idempotent): pakai "if not exists" / "drop policy if
-- exists" supaya tidak error kalau sebagian sudah pernah dibuat sebelumnya.
--
-- Sebelum menjalankan ini, pastikan sudah:
--   1. Membuat Storage bucket "portfolio-assets" (Public bucket) lewat
--      Storage -> New bucket (lihat README bagian 3.3).
--   2. Membuat user admin lewat Authentication -> Users -> Add user
--      (lihat README bagian 4.1) — emailnya akan kamu daftarkan ke tabel
--      `admins` di bagian bawah file ini.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. Storage: izinkan siapa saja MEMBACA file di bucket portfolio-assets
-- ----------------------------------------------------------------------------
drop policy if exists "Public read portfolio-assets" on storage.objects;

create policy "Public read portfolio-assets"
on storage.objects for select
using ( bucket_id = 'portfolio-assets' );


-- ----------------------------------------------------------------------------
-- 2. Tabel allow-list admin (siapa saja yang boleh masuk panel CMS)
-- ----------------------------------------------------------------------------
create table if not exists public.admins (
  email text primary key
);

alter table public.admins enable row level security;

drop policy if exists "Authenticated users can read admin allow-list" on public.admins;

create policy "Authenticated users can read admin allow-list"
on public.admins for select
using ( auth.role() = 'authenticated' );

-- >>> GANTI email di bawah ini dengan email admin kamu yang sudah dibuat
-- >>> lewat Authentication -> Users, lalu jalankan baris ini terpisah kalau
-- >>> baris ini gagal karena email sudah ada (ON CONFLICT DO NOTHING aman).
insert into public.admins (email)
values ('admin@example.com')
on conflict (email) do nothing;


-- ----------------------------------------------------------------------------
-- 3. Tabel konten: portfolio_projects
-- ----------------------------------------------------------------------------
create table if not exists public.portfolio_projects (
  id text primary key,
  zone_id text not null,
  world_x integer not null default 0,
  title text not null,
  description text not null default '',
  image text not null default '',
  link text not null default '',
  tags jsonb not null default '[]'::jsonb
);

alter table public.portfolio_projects enable row level security;

drop policy if exists "Public can read projects" on public.portfolio_projects;
drop policy if exists "Authenticated can manage projects" on public.portfolio_projects;

-- Pengunjung biasa (anon) boleh membaca daftar proyek untuk ditampilkan di game
create policy "Public can read projects"
on public.portfolio_projects for select
using (true);

-- Hanya user yang sudah login (admin) yang boleh menambah/ubah/hapus
create policy "Authenticated can manage projects"
on public.portfolio_projects for all
using ( auth.role() = 'authenticated' )
with check ( auth.role() = 'authenticated' );


-- ----------------------------------------------------------------------------
-- 4. Tabel konten: portfolio_certificates
-- ----------------------------------------------------------------------------
create table if not exists public.portfolio_certificates (
  id text primary key,
  island_x integer not null default 0,
  title text not null,
  issuer text not null default '',
  date text not null default '',
  description text not null default '',
  image text not null default '',
  link text not null default ''
);

alter table public.portfolio_certificates enable row level security;

drop policy if exists "Public can read certificates" on public.portfolio_certificates;
drop policy if exists "Authenticated can manage certificates" on public.portfolio_certificates;

create policy "Public can read certificates"
on public.portfolio_certificates for select
using (true);

create policy "Authenticated can manage certificates"
on public.portfolio_certificates for all
using ( auth.role() = 'authenticated' )
with check ( auth.role() = 'authenticated' );


-- ----------------------------------------------------------------------------
-- 5. (Opsional) Tabel analytics kunjungan — aman dilewati kalau tidak dipakai
-- ----------------------------------------------------------------------------
create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  event_name text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.visits enable row level security;

drop policy if exists "Anyone can insert visit logs" on public.visits;

create policy "Anyone can insert visit logs"
on public.visits for insert
with check (true);


-- ----------------------------------------------------------------------------
-- 6. (Opsional) World epoch bersama untuk siklus musim yang sama ke semua orang
-- ----------------------------------------------------------------------------
create table if not exists public.world_state (
  key text primary key,
  epoch_ms bigint not null
);

alter table public.world_state enable row level security;

drop policy if exists "Public can read world_state" on public.world_state;

create policy "Public can read world_state"
on public.world_state for select
using (true);

-- Contoh isi baris epoch (opsional, sesuaikan epoch_ms dengan waktu launch kamu
-- dalam milliseconds Unix timestamp):
-- insert into public.world_state (key, epoch_ms) values ('launch', 1735689600000)
-- on conflict (key) do nothing;

-- ============================================================================
-- SELESAI. Setelah ini jalan tanpa error, kamu tinggal:
--  1. Ganti 'admin@example.com' di atas dengan email admin asli kamu (kalau
--     belum), lalu jalankan ulang query INSERT itu saja.
--  2. Upload gambar .webp lewat Storage -> portfolio-assets (lihat README 3.4).
--  3. Buka game, klik copyright 10x, login admin, mulai kelola konten.
-- ============================================================================
